[package]
name = "quant_proj"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
serde_json = "1.0"
tokio = { version = "1.48.0", features = ["full"] }
